---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Palm Beah Games.
--- DateTime: 2/19/2019 4:28 PM
---

-- Key array
Keys = {
    ["ESC"] = 322, ["F1"] = 288, ["F2"] = 289, ["F3"] = 170, ["F5"] = 166, ["F6"] = 167, ["F7"] = 168, ["F8"] = 169, ["F9"] = 56, ["F10"] = 57,
    ["~"] = 243, ["1"] = 157, ["2"] = 158, ["3"] = 160, ["4"] = 164, ["5"] = 165, ["6"] = 159, ["7"] = 161, ["8"] = 162, ["9"] = 163, ["-"] = 84, ["="] = 83, ["BACKSPACE"] = 177,
    ["TAB"] = 37, ["Q"] = 44, ["W"] = 32, ["E"] = 46, ["R"] = 45, ["T"] = 245, ["Y"] = 246, ["U"] = 303, ["P"] = 199, ["["] = 39, ["]"] = 40, ["ENTER"] = 18,
    ["CAPS"] = 137, ["A"] = 34, ["S"] = 8, ["D"] = 9, ["F"] = 23, ["G"] = 47, ["H"] = 74, ["K"] = 311, ["L"] = 182,
    ["LEFTSHIFT"] = 21, ["Z"] = 20, ["X"] = 73, ["C"] = 26, ["V"] = 0, ["B"] = 29, ["N"] = 249, ["M"] = 244, [","] = 82, ["."] = 81,
    ["LEFTCTRL"] = 36, ["LEFTALT"] = 19, ["SPACE"] = 22, ["RIGHTCTRL"] = 70,
    ["HOME"] = 213, ["PAGEUP"] = 10, ["PAGEDOWN"] = 11, ["DELETE"] = 178,
    ["LEFT"] = 174, ["RIGHT"] = 175, ["TOP"] = 27, ["DOWN"] = 173,
    ["NENTER"] = 201, ["N4"] = 108, ["N5"] = 60, ["N6"] = 107, ["N+"] = 96, ["N-"] = 97, ["N7"] = 117, ["N8"] = 61, ["N9"] = 118
}

-- Entity blip array
entityBlip = {}

-- Suspects array
suspects = {}

-- actions
Citizen.CreateThread(function()
    -- Register suspect groups
    AddRelationshipGroup("SUSPECTS")
    SetRelationshipBetweenGroups(5, GetHashKey('COP'), GetHashKey("SUSPECTS"));
    SetRelationshipBetweenGroups(5, GetHashKey('SUSPECTS'), GetHashKey("COP"));
    SetRelationshipBetweenGroups(5, GetHashKey('SUSPECTS'), GetHashKey("PLAYER"));
    SetRelationshipBetweenGroups(5, GetHashKey('PLAYER'), GetHashKey("SUSPECTS"));

    while true do
        Citizen.Wait(0)
        if (IsPedInAnyVehicle(playerPed, true) ~= 1) then
            local x, y, z = table.unpack(GetEntityCoords(playerPed, true));

            -- arrest and detain
            if (IsPlayerFreeAiming(PlayerId())) then
                local targetFound, target = GetEntityPlayerIsFreeAimingAt(PlayerId())
                if targetFound then
                    if (IsEntityAPed(target) == 1 and IsPedAPlayer(target) ~= true) then
                        if (HUD.Tips.howToArrest == true) then
                            HUD.Tips.howToArrest = false;
                            HUD.Notification("You can arrest a subject by pressing E while aiming, or press E nearby to detain.");
                        end
                        if IsControlPressed(0, Keys['E']) then
                            TriggerServerEvent('PedManager.orderArrest', target)
                            if (math.random(0, 2) == 1) then
                                TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 0.5, 'officer_freeze_01', 1.0)
                            elseif (math.random(0, 2) == 1) then
                                TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 0.5, 'officer_yellPolice_01', 1.0)
                            else
                                TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 0.5, 'officer_yellPolice_02', 1.0)
                            end
                            Citizen.Wait(1500)
                        end
                    end
                end
            else
                if IsControlPressed(0, Keys['E']) then
                    ReportCrime(playerPed, 11, 0)
                    local nearbyPed = GetNearbyPed(x, y, z, 5.0)
                    if (math.random(0, 2) == 1) then
                        TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 0.5, 'officer_yellPolice_01', 1.0)
                    else
                        TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 0.5, 'officer_yellPolice_02', 1.0)
                    end
                    if (nearbyPed ~= nil and IsEntityAPed(nearbyPed) == 1) then
                        HUD.Notification("Interact with the subject.");
                    else
                        HUD.Notification("There are no nearby subjects to detain.");
                    end
                    Citizen.Wait(1500)
                end
            end
        end
    end
end)

-- identifiers
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(500)
        local x, y, z = table.unpack(GetEntityCoords(playerPed, true));

        -- find any suspect group hashes
        local nearbyPeds = GetNearbyPeds(x, y , z, 150);
        for i, ped in ipairs(nearbyPeds)do
            if (GetPedRelationshipGroupHash(ped) == GetHashKey("SUSPECTS") and DoesBlipExist(entityBlip[ped]) ~= 1 and IsPedDeadOrDying(entityBlip[ped], 1) ~= 1) then
                AddTargetToWanted(ped);
            end
        end

        -- remove suspect blip if none exist
        if(tonumber(#suspects) > 0)then
            SetFakeWantedLevel(1)
            for i, suspect in ipairs(suspects)do
                if(IsEntityAPed(suspect['ped']) ~= 1 or IsPedDeadOrDying(suspect['ped'], 1) == 1)then
                    if(DoesBlipExist(suspect['blip']) == 1)then
                        RemoveBlip(suspect['blip']);
                    end
                    suspects[i] = nil;
                end
            end
        else
            SetFakeWantedLevel(0)
        end
    end
end)

-- listeners
RegisterNetEvent('Interactions.addToWanted')
AddEventHandler('Interactions.addToWanted', function(target)
    AddTargetToWanted(target)
end)
function AddTargetToWanted(target)
    if (IsEntityAPed(target) == 1) then
        SetPedRelationshipGroupHash(target, GetHashKey("SUSPECTS"))
        -- store to suspects array
        local suspectId = tonumber(#suspects) + 1;
        suspects[suspectId]         = {}
        suspects[suspectId]['id']   = suspectId
        suspects[suspectId]['ped']  = target
        entityBlip[target]          = AddBlipForEntity(target, true)
        suspects[suspectId]['blip'] = entityBlip[target]
    end
end

function GetNearbyPeds(X, Y, Z, Radius)
    local NearbyPeds = {}
    if tonumber(X) and tonumber(Y) and tonumber(Z) then
        if tonumber(Radius) then
            for Ped in EnumeratePeds() do
                if DoesEntityExist(Ped) then
                    local PedPosition = GetEntityCoords(Ped, false)
                    local pedDistance = Vdist(X, Y, Z, PedPosition.x, PedPosition.y, PedPosition.z);
                    if (pedDistance <= Radius and IsEntityAPed(Ped) == 1 and Ped ~= playerPed and IsPedAPlayer(Ped) ~= true and GetPedType(Ped) ~= 20 and GetPedType(Ped) ~= 21 and GetPedType(Ped) ~= 27 and GetPedType(Ped) ~= 6) then
                        table.insert(NearbyPeds, Ped)
                    end
                end
            end
        else
            print("GetNearbyPeds was given an invalid radius!")
        end
    else
        print("GetNearbyPeds was given invalid coordinates!")
    end
    return NearbyPeds
end
function GetNearbyPed(X, Y, Z, Radius)
    local NearbyPed = nil;
    local closestPed = Radius;
    if tonumber(X) and tonumber(Y) and tonumber(Z) then
        if tonumber(Radius) then
            for Ped in EnumeratePeds() do
                if DoesEntityExist(Ped) then
                    local PedPosition = GetEntityCoords(Ped, false)
                    local pedDistance = Vdist(X, Y, Z, PedPosition.x, PedPosition.y, PedPosition.z);
                    if (pedDistance <= Radius and pedDistance < closestPed and IsEntityAPed(Ped) == 1 and Ped ~= playerPed and IsPedAPlayer(Ped) ~= true and GetPedType(Ped) ~= 20 and GetPedType(Ped) ~= 21 and GetPedType(Ped) ~= 27 and GetPedType(Ped) ~= 6) then
                        closestPed = pedDistance;
                        NearbyPed = Ped;
                    end
                end
            end
        else
            print("GetNearbyPed was given an invalid radius!")
        end
    else
        print("GetNearbyPed was given invalid coordinates!")
    end
    return NearbyPed
end
function GetNearbyPolice(X, Y, Z, Radius)
    local NearbyPolice = {}
    if tonumber(X) and tonumber(Y) and tonumber(Z) then
        if tonumber(Radius) then
            for Ped in EnumeratePeds() do
                if DoesEntityExist(Ped) then
                    local PedPosition = GetEntityCoords(Ped, false)
                    local pedDistance = Vdist(X, Y, Z, PedPosition.x, PedPosition.y, PedPosition.z);
                    if (pedDistance <= Radius and IsEntityAPed(Ped) == 1 and Ped ~= playerPed and IsPedAPlayer(Ped) ~= true and GetPedType(Ped) == 6) then
                        table.insert(NearbyPolice, Ped)
                    end
                end
            end
        else
            print("GetNearbyPolice was given an invalid radius!")
        end
    else
        print("GetNearbyPolice was given invalid coordinates!")
    end
    return NearbyPolice
end
