---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Palm Beah Games.
--- DateTime: 2/19/2019 5:12 AM
---
SpawnManager = {};
local initialSpawn = true;

AddEventHandler('playerSpawned', function(spawn)
    Citizen.Wait(3000);
    if initialSpawn == true then
        SpawnManager.InitializePlayer()
    end
end)

RegisterCommand('spawn', function(source, args, rawCommand)
    SpawnManager.InitializePlayer()
end)

function SpawnManager.InitializePlayer()
    initialSpawn = false;
    playerPed = GetPlayerPed(-1);
    SetEntityCoords(playerPed, 459.27743530273, -992.36853027344, 30.689586639404, 1, 0, 59.749336242676, 1);
    SetEntityRotation(playerPed, 1, 0, 59.749336242676, 1, 1);
    TriggerServerEvent('selectCharacter')
    Citizen.Wait(1000)
    updateCharacter()
    -- set friendly with public servants.
    SetRelationshipBetweenGroups(0, GetHashKey('PLAYER'), GetHashKey("COP"));
    SetRelationshipBetweenGroups(0, GetHashKey('PLAYER'), GetHashKey("SECURITY_GUARD"));
    SetRelationshipBetweenGroups(0, GetHashKey('PLAYER'), GetHashKey("FIREMAN"));
    SetRelationshipBetweenGroups(0, GetHashKey('PLAYER'), GetHashKey("ARMY"));
    SetRelationshipBetweenGroups(0, GetHashKey('PLAYER'), GetHashKey("MEDIC"));
    SetRelationshipBetweenGroups(0, GetHashKey('COP'), GetHashKey("PLAYER"));
    SetRelationshipBetweenGroups(0, GetHashKey('SECURITY_GUARD'), GetHashKey("PLAYER"));
    SetRelationshipBetweenGroups(0, GetHashKey('FIREMAN'), GetHashKey("PLAYER"));
    SetRelationshipBetweenGroups(0, GetHashKey('ARMY'), GetHashKey("PLAYER"));
    SetRelationshipBetweenGroups(0, GetHashKey('MEDIC'), GetHashKey("PLAYER"));
    -- clear player weapons & give police weapons
    RemoveAllPedWeapons(PlayerPedId(), true);
    GiveWeaponToPed(PlayerPedId(), GetHashKey("WEAPON_PISTOL"), 9999, false, false);
    GiveWeaponToPed(PlayerPedId(), GetHashKey("WEAPON_PUMPSHOTGUN"), 9999, false, false);
    GiveWeaponToPed(PlayerPedId(), GetHashKey("WEAPON_NIGHTSTICK"), 9999, false, false);
    GiveWeaponToPed(PlayerPedId(), GetHashKey("WEAPON_STUNGUN"), 9999, false, false);
    GiveWeaponToPed(PlayerPedId(), GetHashKey("WEAPON_FLASHLIGHT"), 9999, false, false);
    -- set as cop
    SetPedAsCop(playerPed, true)
end