---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Palm Beah Games.
--- DateTime: 2/19/2019 3:25 PM
---

RegisterServerEvent('savePlayerRank')
AddEventHandler('savePlayerRank', function(playerRank, playerExp, playerExpGoal)

    local playerID = GetPlayerIdentifier(source)

    MySQL.ready(function()
        MySQL.Async.execute('UPDATE `characters` SET `rank`=@rank,`exp`=@exp,`exp_goal`=@expGoal WHERE `player_id`=@player_id', {
            ['rank']  = playerRank,
            ['exp'] = playerExp,
            ['expGoal'] = playerExpGoal,
            ['player_id'] = playerID
        }, function(rowsChanged)
        end)
    end)
end)