---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Palm Beah Games.
--- DateTime: 2/19/2019 5:18 PM
---

PedManager = {}

-- Ped Suspects
PedManager.suspects = {}

RegisterServerEvent('PedManager.makeSuspect')
AddEventHandler('PedManager.makeSuspect', function(target)
    local players = GetPlayers()
    for _, i in ipairs(players) do
        TriggerClientEvent('Interactions.addToWanted', i, target)
    end
end)
